// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGQ0N3EPSnM9-aUVewnzyqzn3iZ9211wE',
    appId: '1:504369550146:web:2012c8331ed44b83a6eedb',
    messagingSenderId: '504369550146',
    projectId: 'example-20efe',
    authDomain: 'example-20efe.firebaseapp.com',
    databaseURL: 'https://example-20efe-default-rtdb.firebaseio.com',
    storageBucket: 'example-20efe.appspot.com',
    measurementId: 'G-L4MYBBW5LB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHseFBGckA1eB5Nn-EoF53DIOBZI1KOVU',
    appId: '1:504369550146:android:aa3f656f319a4adba6eedb',
    messagingSenderId: '504369550146',
    projectId: 'example-20efe',
    databaseURL: 'https://example-20efe-default-rtdb.firebaseio.com',
    storageBucket: 'example-20efe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEIzMJzPLpR8aRx8GpAjlOjg8yjPrnyZA',
    appId: '1:504369550146:ios:644238a2cfec4a9fa6eedb',
    messagingSenderId: '504369550146',
    projectId: 'example-20efe',
    databaseURL: 'https://example-20efe-default-rtdb.firebaseio.com',
    storageBucket: 'example-20efe.appspot.com',
    iosBundleId: 'com.rollcake.honeybee',
  );
}
